# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppAnswers',
            fields=[
                ('pk_answer', models.CharField(default='d0b28cdc094711e79638c3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='回答id')),
                ('pk_question', models.CharField(blank=True, max_length=40, null=True, verbose_name='提问id')),
                ('pk_user', models.CharField(blank=True, max_length=40, null=True, verbose_name='用户id')),
                ('voice', models.CharField(blank=True, max_length=200, null=True, verbose_name='音频路径')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='时长')),
                ('picture', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(blank=True, null=True, verbose_name='文本内容')),
                ('isbest', models.NullBooleanField(verbose_name='是否最佳')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '回答',
                'verbose_name_plural': '回答列表',
                'db_table': 'app_answers',
            },
        ),
        migrations.CreateModel(
            name='AppListens',
            fields=[
                ('pk_listen', models.CharField(default='d0b28cdd094711e7982dc3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='id')),
                ('pk_question', models.CharField(blank=True, max_length=40, null=True, verbose_name='提问id')),
                ('pk_respondent', models.CharField(blank=True, max_length=40, null=True, verbose_name='回答者')),
                ('pk_user', models.CharField(blank=True, max_length=40, null=True, verbose_name='用户')),
                ('iscommented', models.NullBooleanField(verbose_name='是否已评论')),
                ('ispaid', models.NullBooleanField(verbose_name='是否已支付')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('upatetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '偷听',
                'verbose_name_plural': '偷听列表',
                'db_table': 'app_listens',
            },
        ),
        migrations.CreateModel(
            name='AppQuestionComments',
            fields=[
                ('pk_comment', models.CharField(default='d0b28cde094711e7af98c3088f08b8fe', max_length=40, primary_key=True, serialize=False)),
                ('pk_question', models.CharField(blank=True, max_length=40, null=True)),
                ('pk_user', models.CharField(blank=True, max_length=40, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_question_comments',
            },
        ),
        migrations.CreateModel(
            name='AppQuestionGoods',
            fields=[
                ('pk_key', models.CharField(default='d0b28cdf094711e7a268c3088f08b8fe', max_length=40, primary_key=True, serialize=False)),
                ('pk_question', models.CharField(blank=True, max_length=40, null=True)),
                ('pk_user', models.CharField(blank=True, max_length=40, null=True)),
                ('createtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_question_goods',
            },
        ),
        migrations.CreateModel(
            name='AppQuestions',
            fields=[
                ('pk_question', models.CharField(default='d0b02bac094711e7bf08c3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='问答id')),
                ('pk_user', models.CharField(blank=True, max_length=40, null=True, verbose_name='用户id')),
                ('content', models.TextField(null=True, verbose_name='提问内容')),
                ('questionmode', models.CharField(choices=[('free', '免费提问'), ('push', '付费提问'), ('onetoone', '一对一提问')], max_length=20, null=True, verbose_name='提问方式')),
                ('questionrelate', models.CharField(blank=True, max_length=20, null=True, verbose_name='提问相关')),
                ('pk_respondent', models.CharField(blank=True, max_length=40, null=True, verbose_name='回复者id')),
                ('listennum', models.IntegerField(default=0, null=True, verbose_name='偷听人数')),
                ('isopen', models.NullBooleanField(verbose_name='是否公开')),
                ('iscommented', models.NullBooleanField(verbose_name='是否已评论')),
                ('question_price', models.DecimalField(decimal_places=4, max_digits=18, null=True, verbose_name='提问价格')),
                ('listen_price', models.DecimalField(decimal_places=4, max_digits=18, null=True, verbose_name='偷听价格')),
                ('isaudited', models.NullBooleanField(verbose_name='是否审核')),
                ('goodnum', models.IntegerField(default=0, null=True, verbose_name='点赞数')),
                ('commentnum', models.IntegerField(default=0, null=True, verbose_name='评论数')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('re_status', models.IntegerField(blank=True, null=True, verbose_name='状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('re_createtime', models.DateTimeField(blank=True, null=True, verbose_name='追问创建时间')),
                ('race_endtime', models.DateTimeField(blank=True, null=True, verbose_name='悬赏结束时间')),
                ('opentime', models.DateTimeField(blank=True, null=True, verbose_name='公开时间')),
                ('updatetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '提问',
                'verbose_name_plural': '提问列表',
                'db_table': 'app_questions',
            },
        ),
    ]
