# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-03-15 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appanswers',
            name='pk_answer',
            field=models.CharField(default='4b71e9d3094811e7bf13c3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='回答id'),
        ),
        migrations.AlterField(
            model_name='applistens',
            name='pk_listen',
            field=models.CharField(default='4b71e9d4094811e79b0bc3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='appquestioncomments',
            name='pk_comment',
            field=models.CharField(default='4b71e9d5094811e780f3c3088f08b8fe', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appquestiongoods',
            name='pk_key',
            field=models.CharField(default='4b71e9d6094811e78cbec3088f08b8fe', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appquestions',
            name='pk_question',
            field=models.CharField(default='4b71e9d2094811e78806c3088f08b8fe', max_length=40, primary_key=True, serialize=False, verbose_name='问答id'),
        ),
    ]
